import type { GameConfigDoc } from './types.js';

export const defaultGameConfigs: GameConfigDoc[] = [
  {
    gameId: 'snake',
    name: 'Snake',
    category: 'arcade',
    description: 'Classic snake — eat, grow, avoid walls.',
    difficulties: ['easy', 'normal', 'hard'],
    settings: { tickMs: { easy: 180, normal: 140, hard: 100 }, grid: 20 },
  },
  {
    gameId: 'tic-tac-toe',
    name: 'Tic Tac Toe',
    category: 'arcade',
    description: 'X vs O on a 3×3 grid.',
    difficulties: ['easy', 'medium'],
    settings: { aiDepth: { easy: 1, medium: 9 } },
  },
  {
    gameId: 'brick-breaker',
    name: 'Brick Breaker',
    category: 'arcade',
    description: 'Break bricks with the ball.',
    difficulties: ['normal', 'hard'],
    settings: { rows: 5, cols: 8, ballSpeed: 6 },
  },
  {
    gameId: 'bubble-shooter',
    name: 'Bubble Shooter',
    category: 'arcade',
    description: 'Match colors to clear the cluster.',
    difficulties: ['normal'],
    settings: { colors: 5, rows: 8 },
  },
  {
    gameId: 'maze',
    name: 'Maze',
    category: 'arcade',
    description: 'Reach the goal through a generated maze.',
    difficulties: ['small', 'medium', 'large'],
    settings: { sizes: { small: 11, medium: 17, large: 23 } },
  },
  {
    gameId: 'jigsaw',
    name: 'Jigsaw',
    category: 'puzzle',
    description: 'Drag pieces to rebuild the image.',
    difficulties: ['easy', 'medium', 'hard'],
    settings: { pieces: { easy: 9, medium: 16, hard: 25 } },
  },
  {
    gameId: 'block-puzzle',
    name: 'Block Puzzle',
    category: 'puzzle',
    description: 'Drag blocks onto the grid to clear lines.',
    difficulties: ['normal'],
    settings: { grid: 8 },
  },
  {
    gameId: 'crossword',
    name: 'Crossword',
    category: 'puzzle',
    description: 'Fill the grid from clues.',
    difficulties: ['daily'],
    settings: { gridSize: 5 },
  },
  {
    gameId: 'math-quiz',
    name: 'Math Quiz',
    category: 'puzzle',
    description: 'Answer fast — streaks multiply your score.',
    difficulties: ['easy', 'medium', 'hard'],
    settings: { timeLimitSec: 8, rounds: 10 },
  },
  {
    gameId: 'magic-sort',
    name: 'Magic Sort',
    category: 'puzzle',
    description: 'Sort colored balls into matching tubes.',
    difficulties: ['normal'],
    settings: { tubes: 5, colors: 4 },
  },
  {
    gameId: 'idle-clicker',
    name: 'Idle Clicker',
    category: 'action',
    description: 'Tap, upgrade, grow your numbers.',
    difficulties: ['casual'],
    settings: { baseClick: 1 },
  },
  {
    gameId: 'plinko',
    name: 'Plinko',
    category: 'action',
    description: 'Drop a chip and land multipliers.',
    difficulties: ['normal'],
    settings: { pegRows: 10, pins: 9 },
  },
  {
    gameId: 'spin-wheel',
    name: 'Spin Wheel',
    category: 'action',
    description: 'Spin for points and bonus rounds.',
    difficulties: ['normal'],
    settings: { sectors: 8 },
  },
  {
    gameId: 'dice-game',
    name: 'Dice Game',
    category: 'action',
    description: 'Roll dice, beat the house target.',
    difficulties: ['normal'],
    settings: { rounds: 5 },
  },
  {
    gameId: 'endless-runner',
    name: 'Endless Runner',
    category: 'runner',
    description: 'Jump obstacles — speed increases over time.',
    difficulties: ['normal'],
    settings: { gravity: 0.65, jump: -12 },
  },
  {
    gameId: 'car-runner',
    name: 'Car Runner',
    category: 'runner',
    description: 'Switch lanes to dodge traffic.',
    difficulties: ['normal'],
    settings: { lanes: 3, speed: 5 },
  },
  {
    gameId: 'match-3',
    name: 'Match-3',
    category: 'match',
    description: 'Swap adjacent gems to match three.',
    difficulties: ['normal'],
    settings: { size: 8, types: 6 },
  },
  {
    gameId: 'bubble-pop',
    name: 'Bubble Pop',
    category: 'match',
    description: 'Pop connected groups of the same color.',
    difficulties: ['normal'],
    settings: { colors: 5, rows: 10, cols: 8 },
  },
];
